name: Site Deployment

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install modules and Build Site
        run: yarn install && yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
